### ISSUE TITLE
malscan cant exec

### ISSUE THREAD

**Issue by vay3t** [malscan/malscan#26]
when i run malscan told me this message "Malscan is currently running in process 27946. Exiting." i view process but not exist malscan

**Comment by jgrancell** [comment]
This is because the lock file found at APPLICATION_PATH/malscan.lock still exists, probably from an aborted scan. If you're sure no scan is running, you can delete the lock file manually.

**Comment by jgrancell** [comment]
v1.8.1 has been released to add more details to the applications' output when this issue is encountered.
